# Generated by Django 4.2.16 on 2024-10-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название породы')),
                ('foto', models.ImageField(upload_to='img/', verbose_name='Картинка')),
                ('description', models.TextField(verbose_name='Описание породы')),
            ],
        ),
    ]
