# Generated by Django 4.2.16 on 2024-09-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя покупателя(username аккаунта)')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Ваш баланс')),
                ('age', models.IntegerField(verbose_name='Ваш возраст')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название игры')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Цена')),
                ('size', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Размер файлов игры')),
                ('description', models.TextField(verbose_name='Описание игры')),
                ('age_limited', models.BooleanField(default=False, verbose_name='Ограничение возраста 18+')),
                ('buyer', models.ManyToManyField(to='task1.buyer', verbose_name='Обладатель книги')),
            ],
        ),
    ]
