# Generated by Django 4.2.16 on 2024-09-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название породы')),
                ('foto', models.ImageField(height_field=200, upload_to='img/', verbose_name='Картинка', width_field=300)),
                ('description', models.TextField(verbose_name='Описание породы')),
            ],
        ),
        migrations.AlterField(
            model_name='buyer',
            name='balance',
            field=models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Ваш баланс'),
        ),
        migrations.AlterField(
            model_name='game',
            name='cost',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='game',
            name='size',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Размер файлов игры'),
        ),
    ]
