# Generated by Django 4.2.16 on 2024-10-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_dogs_alter_buyer_balance_alter_game_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dogs',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='dogs',
            name='foto',
            field=models.ImageField(height_field=500, upload_to='img/', verbose_name='Картинка', width_field=700),
        ),
    ]
