# Generated by Django 4.2.16 on 2024-10-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_rename_title_dogs_name_alter_dogs_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogs',
            name='foto',
            field=models.ImageField(upload_to='img/', verbose_name='Картинка'),
        ),
    ]
