# Generated by Django 4.2.16 on 2024-10-05 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0004_alter_dogs_foto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dogs',
        ),
    ]
